### ISSUE TITLE
Feature Request: Add NTP Configuration to the IP Configuration

### ISSUE THREAD

**Issue by kentbrock** [patience4711/read-APSystems-YC600-QS1#12]
This is more or less a feature request and I am not sure where to adress things like that :-) 

It would be great to have the option to change the ntp server in the IP configuration section. My complete homeautomation is synced to my own ntp server. This means that all data from all systems have the same time stamp. This helps with the evaluation of the data.

**Comment by patience4711** [comment]
Sorry no time for that.
